http:
  host: "0.0.0.0"
  port: 8080

redis:
  host: 172.17.29.75
  port: 6379

kafka:
  bootstrap_servers: 172.17.29.75:9092
  group_id: ceramicraft_ai_secure_agent_group

mysql:
  host: 172.17.29.75
  port: 3306
  username: root
  database: admin_db
  max_connect_size: 5
