redis:
  host: 10.249.171.135
  port: 6379

kafka:
  bootstrap_servers: 10.249.171.135:9092
  group_id: ceramicraft_ai_secure_agent_group

mysql:
  host: 10.249.171.135
  port: 3306
  username: root
  database: admin_db
  max_connect_size: 5
