redis:
  host: 10.249.91.72
  port: 6379

kafka:
  bootstrap_servers: 10.249.91.72:9092
  group_id: ceramicraft_ai_secure_agent_group

mysql:
  host: 10.249.91.72
  port: 3306
  username: root
  password: changeit
  database: admin_db
  max_connect_size: 5
